.Sh NAME
.Nm disco-search
.Nd search, edit and update DiscoDOS releases and tracks

.Sh DESCRIPTION
the
.Cm search
command
searches for releases and tracks in the Discogs
collection. Several actions can be executed on the
found items, eg. adding to a mix, updating track info
from Discogs or fetching additional information from
MusicBrainz/AcousticBrainz or simply adding track information by hand (user-defined BPM/key, track notes, user-defined AcousticBrainz recording ID).

.Sh EXAMPLES
.Pp
Step by step tutorials and in-detail explanations of all DiscoDOS commands can be found on the README and User's Manual pages:
.Lk https://github.com/JOJ0/discodos/blob/master/README.md
.Lk https://github.com/JOJ0/discodos/blob/master/MANUAL.md
...

...
.Sh AUTHORS
J0J0 T <jt@peek-a-boo.at>
.Pp
Special thanks go to Samplissimo for testing and feature ideas, to Schobernoise for motivation and a GUI draft and most of all to Gold Fisch for her patience while Doogie Howser wrote in his diary!
...
