.Sh NAME
.Nm disco-mix
.Nd manage your DiscoDOS mixes

.Sh DESCRIPTION
the
.Cm mix
command is used to manage your DiscoDOS mixes. A mix is basically just a list of tracks in a specific order, a playlist, a track pool, you name it.
...

.Sh AUTHORS
J0J0 T <jt@peek-a-boo.at>
.Pp
Special thanks go to Samplissimo for testing and feature ideas, to Schobernoise for motivation and a GUI draft and most of all to Gold Fish for her patience while Doogie Howser wrote in his diary!
...

