.Sh DESCRIPTION
.Pp
discosync is used to save the DiscoBASE to the cloud and restore it if something went wrong. It also can be used to share it between multiple computers. There are currently two options for storing the backups:

.Pp
.Bl -bullet -compact
.It
Dropbox
.It
A folder on a webserver
.El

.Pp
To set up discosync please follow the configuration steps in the DiscoDOS manual:
https://github.com/JOJ0/discodos/blob/master/MANUAL.md#discosync---the-discodos-backup--sync-tool 
...

.Sh AUTHORS
J0J0 T <jt@peek-a-boo.at>
.Pp
Special thanks go to Samplissimo for testing and feature ideas, to Schobernoise for motivation and a GUI draft and most of all to Gold Fish for her patience while Doogie Howser wrote in his diary!
...
