.Sh NAME
.Nm disco-suggest
.Nd suggest DiscoDOS tracks based on certain criteria

.Sh DESCRIPTION
the
.Cm suggest
command suggests tracks based on what you've played before or
views tracks based on BPM or musical key. 

...
.Sh AUTHORS
J0J0 T <jt@peek-a-boo.at>
.Pp
Special thanks go to Samplissimo for testing and feature ideas, to Schobernoise for motivation and a GUI draft and most of all to Gold Fisch for her patience while Doogie Howser wrote in his diary!
...
