#!/bin/sh
#This script was autogenerated with the --create-script option of cli2man

function man_disco() {
    cli2man -i man/disco_help.txt --see-also disco_mix,disco-suggest,disco-import,disco-search --os Linux --include man/disco_additional.mdoc
}
function man_disco_mix() {
    cli2man -i man/disco_mix_help.txt --see-also disco,disco-suggest,disco-import,disco-search --os Linux
}
function man_disco_suggest() {
    cli2man -i man/disco_suggest_help.txt --see-also disco,disco-mix,disco-import,disco-search --os Linux
}
function man_disco_import() {
    cli2man -i man/disco_import_help.txt --see-also disco,disco-mix,disco-suggest,disco-search --os Linux
}
function man_disco_search() {
    cli2man -i man/disco_search_help.txt --see-also disco,disco-mix,disco-suggest,disco-import --os Linux
}

if [ "$1" == 'doit' ]; then
    man_disco > man/disco.mdoc
    man_disco_mix > man/disco-mix.mdoc
    man_disco_suggest > man/disco-suggest.mdoc
    man_disco_import > man/disco-import.mdoc
    man_disco_search > man/disco-search.mdoc
    echo "5 files written to man/"
    echo "Now fix stuff manually"
else
    man_disco -m
    man_disco_mix -m
    man_disco_suggest -m
    man_disco_import -m
    man_disco_search -m
fi


