"""
This is a setup.py script generated by py2applet

Usage:
    python setup_macapp.py py2app
"""

from setuptools import setup

APP = ['discodos/cmd/open_shell_mac.py']
#APP = ['discodos/cmd/cli.py']
DATA_FILES = ['assets/discodos_cmds_v0.3_white.png']
OPTIONS = {
    'iconfile': 'assets/discodos_7-v6_big_fat_D_128x128.ico',
    #'iconfile': 'assets/default.ico',
    'argv_emulation': 'true',
    'emulate_shell_environment': 'true',
    'verbose': 'true',
    'plist': {
        'CFBundleVersion': '1.0_rc3',
        'CFBundleShortVersionString': '1.0_rc3',
        'CFBundleName': 'DiscoDOS',
        'CFBundleDisplayName': 'DiscoDOS',
        'CFBundleGetInfoString': 'DiscoDOS is the geekiest DJ tool on the planet',
        'CFBundleIdentifier': 'net.jojotodos.discodos',
        'NSAppleScriptEnable': 'true',
        'NSAppleScriptEnabled': 'true',
        'NSHumanReadableCopyright': 'J0J0 T (jt@peek-a-boo.at) - GPL v3'
    }
}

#SCRIPTS=['discodos/cmd/cli.py', 'discodos/cmd/sync.py']

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    #extra_scripts=SCRIPTS,
)
