name: Draft GitHub Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: ncipollo/release-action@v1
        # ref.: https://github.com/ncipollo/release-action
        with:
          name: ${{ github.ref_name }}
          draft: true
          generateReleaseNotes: true
