name: Deploy to test.pypi.org

on:
  release:
    types:
      # - published
      - released
    workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # needs: ["release"]

    environment:
      name: testpypi
      url: https://test.pypi.org/p/discodos
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build distribution
        run: |
           python -m build
           twine check dist/*
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Download all the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
